name: Deploy to Cloud Run

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Terraform Init
        run: |
          cd terraform/environments/prod
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform/environments/prod
          terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          cd terraform/environments/prod
          terraform apply -auto-approve

      - name: Build and Push Container
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/portfolio:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/portfolio:${{ github.sha }}

      - name: Update Container Image
        run: |
          cd terraform/environments/prod
          terraform apply -auto-approve \
            -var="container_image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/portfolio:${{ github.sha }}"
